from nodo import *
from grafo import *


g=Grafo("Mi grafo 1")
print(g)
	
g.agragarNodo("r")
g.agragarNodo("s")
g.agragarNodo("t")
g.agragarNodo("u")
g.agragarNodo("v")
g.agragarNodo("w")
g.agragarNodo("x")
g.agragarNodo("y")
	
	
print(g)
	
print(g.obtenerNombresNodos())

r=g.obtenerNodo("r")
r.agregarVecino("s",1)
r.agregarVecino("v",1)
s=g.obtenerNodo("s")
s.agregarVecino("r",1)
s.agregarVecino("w",1)
t=g.obtenerNodo("t")
t.agregarVecino("u",1)
t.agregarVecino("w",1)
t.agregarVecino("x",1)
u=g.obtenerNodo("u")
u.agregarVecino("t",1)
u.agregarVecino("x",1)
u.agregarVecino("y",1)
v=g.obtenerNodo("v")
v.agregarVecino("r",1)
w=g.obtenerNodo("w")
w.agregarVecino("s",1)
w.agregarVecino("t",1)
w.agregarVecino("x",1)
x=g.obtenerNodo("x")
x.agregarVecino("t",1)
x.agregarVecino("u",1)
x.agregarVecino("w",1)
x.agregarVecino("y",1)
y=g.obtenerNodo("y")
y.agregarVecino("x",1)
y.agregarVecino("u",1)
print(r.obtenerVecinos())
print(s.obtenerVecinos())
print(t.obtenerVecinos())
print(u.obtenerVecinos())
print(v.obtenerVecinos())
print(w.obtenerVecinos())
print(x.obtenerVecinos())
print(y.obtenerVecinos())
	
g.busquedaAmplitud("s")
g.imprimirNodos()
ruta=g.ruta("y",None)
print(ruta)
	
