#include "animacion.h"
#include <QPainter>
#include <qdebug.h>

animacion::animacion(QWidget *parent, int t) :
    QWidget(parent)
{
    x = y = 0;
    tt=t;
    d=new carro*[t];
    for(int j=0;j<tt;j++)
    {
        d[j]=new carro[5];
    }
}

void animacion::paintEvent(QPaintEvent *)
{
    QString a;
    QPainter painter(this);
    painter.setBrush(Qt::white);
    painter.drawRect(0,0,width() -1,height() -1);

   for(int i=0;i<tt;i++)
   {
        //qDebug()<<this->d[i].res_V();
       if((this->d[i][0].res_V())==-1)
       {
           painter.setBrush(Qt::white);
           painter.setPen(Qt::black);
           painter.drawEllipse((i*20),160,20,20);
           a="";
           painter.drawText((i*20)+8,175,a);
       }
       else
       {
           if((this->d[i][0].res_V())==0)
           {
               painter.setBrush(Qt::red);
               painter.setPen(Qt::black);
               painter.drawEllipse((i*20),160,20,20);
               a=QString::number(this->d[i][0].res_X());
               painter.drawText((i*20)+8,175,a);
           }
           else
           {
               painter.setBrush(Qt::green);
               painter.setPen(Qt::black);
               painter.drawEllipse((i*20),160,20,20);
               a=QString::number(this->d[i][0].res_X());
               painter.drawText((i*20)+8,175,a);
           }
       }
   }
   for(int i=0;i<tt;i++)
   {
        //qDebug()<<this->d[i].res_V();
       if((this->d[i][1].res_V())==-1)
       {
           painter.setBrush(Qt::white);
           painter.setPen(Qt::black);
           painter.drawEllipse((i*20),320,20,20);
           a="";
           painter.drawText((i*20)+8,335,a);
       }
       else
       {
           if((this->d[i][1].res_V())==0)
           {
               painter.setBrush(Qt::red);
               painter.setPen(Qt::black);
               painter.drawEllipse((i*20),320,20,20);
               a=QString::number(this->d[i][1].res_X());
               painter.drawText((i*20)+8,335,a);
           }
           else
           {
               painter.setBrush(Qt::green);
               painter.setPen(Qt::black);
               painter.drawEllipse((i*20),320,20,20);
               a=QString::number(this->d[i][1].res_X());
               painter.drawText((i*20)+8,335,a);
           }
       }
   }
   for(int i=0;i<tt;i++)
   {
        //qDebug()<<this->d[i].res_V();
       if((this->d[i][2].res_V())==-1)
       {
           painter.setBrush(Qt::white);
           painter.setPen(Qt::black);
           painter.drawEllipse((i*20),480,20,20);
           a="";
           painter.drawText((i*20)+8,495,a);
       }
       else
       {
           if((this->d[i][2].res_V())==0)
           {
               painter.setBrush(Qt::red);
               painter.setPen(Qt::black);
               painter.drawEllipse((i*20),480,20,20);
               a=QString::number(this->d[i][2].res_X());
               painter.drawText((i*20)+8,495,a);
           }
           else
           {
               painter.setBrush(Qt::green);
               painter.setPen(Qt::black);
               painter.drawEllipse((i*20),480,20,20);
               a=QString::number(this->d[i][2].res_X());
               painter.drawText((i*20)+8,495,a);
           }
       }
   }
   for(int i=0;i<tt;i++)
   {
        //qDebug()<<this->d[i].res_V();
       if((this->d[i][3].res_V())==-1)
       {
           painter.setBrush(Qt::white);
           painter.setPen(Qt::black);
           painter.drawEllipse(440,(i*20),20,20);
           a="";
           painter.drawText(448,(i*20)+15,a);
       }
       else
       {
           if((this->d[i][3].res_V())==0)
           {
               painter.setBrush(Qt::red);
               painter.setPen(Qt::black);
               painter.drawEllipse(440,(i*20),20,20);
               a=QString::number(this->d[i][3].res_X());
               painter.drawText(448,(i*20)+15,a);
           }
           else
           {
               painter.setBrush(Qt::green);
               painter.setPen(Qt::black);
               painter.drawEllipse(440,(i*20),20,20);
               a=QString::number(this->d[i][3].res_X());
               painter.drawText(448,(i*20)+15,a);
           }
       }
   }
   for(int i=0;i<tt;i++)
   {
        //qDebug()<<this->d[i].res_V();
       if((this->d[i][4].res_V())==-1)
       {
           painter.setBrush(Qt::white);
           painter.setPen(Qt::black);
           painter.drawEllipse(880,(i*20),20,20);
           a="";
           painter.drawText(888,(i*20)+15,a);
       }
       else
       {
           if((this->d[i][4].res_V())==0)
           {
               painter.setBrush(Qt::red);
               painter.setPen(Qt::black);
               painter.drawEllipse(880,(i*20),20,20);
               a=QString::number(this->d[i][4].res_X());
               painter.drawText(888,(i*20)+15,a);
           }
           else
           {
               painter.setBrush(Qt::green);
               painter.setPen(Qt::black);
               painter.drawEllipse(880,(i*20),20,20);
               a=QString::number(this->d[i][4].res_X());
               painter.drawText(888,(i*20)+15,a);
           }
       }
   }
   if((this->d[22][0].res_V())!=-1)
   {
       if((this->d[22][0].res_V())==0)
       {
           painter.setBrush(Qt::red);
           painter.setPen(Qt::black);
           painter.drawEllipse((22*20),160,20,20);
           a=QString::number(this->d[22][0].res_X());
           painter.drawText((22*20)+8,175,a);
       }
       else
       {
           painter.setBrush(Qt::green);
           painter.setPen(Qt::black);
           painter.drawEllipse((22*20),160,20,20);
           a=QString::number(this->d[22][0].res_X());
           painter.drawText((22*20)+8,175,a);
       }
   }
   if((this->d[44][0].res_V())!=-1)
   {
       if((this->d[44][0].res_V())==0)
       {
           painter.setBrush(Qt::red);
           painter.setPen(Qt::black);
           painter.drawEllipse((44*20),160,20,20);
           a=QString::number(this->d[44][0].res_X());
           painter.drawText((44*20)+8,175,a);
       }
       else
       {
           painter.setBrush(Qt::green);
           painter.setPen(Qt::black);
           painter.drawEllipse((44*20),160,20,20);
           a=QString::number(this->d[44][0].res_X());
           painter.drawText((44*20)+8,175,a);
       }
   }
   if((this->d[22][1].res_V())!=-1)
   {
       if((this->d[22][1].res_V())==0)
       {
           painter.setBrush(Qt::red);
           painter.setPen(Qt::black);
           painter.drawEllipse((22*20),320,20,20);
           a=QString::number(this->d[22][1].res_X());
           painter.drawText((22*20)+8,335,a);
       }
       else
       {
           painter.setBrush(Qt::green);
           painter.setPen(Qt::black);
           painter.drawEllipse((22*20),320,20,20);
           a=QString::number(this->d[22][1].res_X());
           painter.drawText((22*20)+8,335,a);
       }
   }
   if((this->d[44][1].res_V())!=-1)
   {
       if((this->d[44][1].res_V())==0)
       {
           painter.setBrush(Qt::red);
           painter.setPen(Qt::black);
           painter.drawEllipse((44*20),320,20,20);
           a=QString::number(this->d[44][1].res_X());
           painter.drawText((44*20)+8,335,a);
       }
       else
       {
           painter.setBrush(Qt::green);
           painter.setPen(Qt::black);
           painter.drawEllipse((44*20),320,20,20);
           a=QString::number(this->d[44][1].res_X());
           painter.drawText((44*20)+8,335,a);
       }
   }
   if((this->d[22][2].res_V())!=-1)
   {
       if((this->d[22][2].res_V())==0)
       {
           painter.setBrush(Qt::red);
           painter.setPen(Qt::black);
           painter.drawEllipse((22*20),480,20,20);
           a=QString::number(this->d[22][2].res_X());
           painter.drawText((22*20)+8,495,a);
       }
       else
       {
           painter.setBrush(Qt::green);
           painter.setPen(Qt::black);
           painter.drawEllipse((22*20),480,20,20);
           a=QString::number(this->d[22][2].res_X());
           painter.drawText((22*20)+8,495,a);
       }
   }
   if((this->d[44][2].res_V())!=-1)
   {
       if((this->d[44][2].res_V())==0)
       {
           painter.setBrush(Qt::red);
           painter.setPen(Qt::black);
           painter.drawEllipse((44*20),480,20,20);
           a=QString::number(this->d[44][2].res_X());
           painter.drawText((44*20)+8,495,a);
       }
       else
       {
           painter.setBrush(Qt::green);
           painter.setPen(Qt::black);
           painter.drawEllipse((44*20),480,20,20);
           a=QString::number(this->d[44][2].res_X());
           painter.drawText((44*20)+8,495,a);
       }
   }
}
void animacion::mover(int x, int y)
{
    this->x += x;
    this->y += y;
    update();
}

void animacion::dar_d(carro **v)
{
    for(int i=0;i<tt;i++)
    {
        for(int j=0;j<5;j++)
        {
            this->d[i][j]=v[i][j];
        }
    }
}
